# Generated by Django 2.1.2 on 2020-04-12 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_sentence'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sentence',
            options={'ordering': ['parent_post', 'sentence_index']},
        ),
    ]
